[workspace]
resolver = "2"
members = [
    "crates/env",
    "crates/conf",
    "crates/infra",
    "crates/logger",
    "crates/utils"
]


[workspace.dependencies.dev]

[workspace.dependencies.test]

[workspace.dependencies.release]